# Put this file in %APPDATA%/lazygit
notARepository: 'skip'
gui:
  language: 'en'
  showIcons: true
  theme:
    activeBorderColor:
      - yellow
      - bold
    inactiveBorderColor:
      - '#367fe6'
    optionsTextColor:
      - '#367fe6'
    selectedLineBgColor:
      - '#367fe6'
    selectedRangeBgColor:
      - '#367fe6'
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - magenta
    defaultFgColor:
      - white
